# Generated by Django 4.2.4 on 2023-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes',
            old_name='nombre_cliente',
            new_name='nombreCliente',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
